services:
    _defaults:
        public: false
        autoconfigure: true
        autowire: true

    TomvdPeet\BreadcrumbBundle\:
        resource: '../../*'
        exclude: '../../{Attribute,Resources}'

    TomvdPeet\BreadcrumbBundle\BreadcrumbTrail\Trail:
        calls:
            - setTemplate: ['%tomvd_peet_breadcrumb.template%']

    TomvdPeet\BreadcrumbBundle\Loader\BreadcrumbLoaderInterface:
        alias: TomvdPeet\BreadcrumbBundle\Loader\AttributeBreadcrumbLoader

    TomvdPeet\BreadcrumbBundle\EventListener\BreadcrumbListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: -1 }
