services:
    _defaults:
        public: false
        autoconfigure: true
        autowire: true

    TomvdPeet\BreadcrumbBundle\:
        resource: '../../*'
        exclude: '../../{Attribute,Resources}'

    TomvdPeet\BreadcrumbBundle\BreadcrumbTrail\Trail:
        calls:
            - setTemplate: ['%tomvd_peet_breadcrumb.template%']

    TomvdPeet\BreadcrumbBundle\Loader\CompiledBreadcrumbLoader:
        arguments:
            $cacheFile: '%tomvd_peet_breadcrumb.cache_file%'
            $fallbackLoader: '@TomvdPeet\BreadcrumbBundle\Loader\ParentRouteBreadcrumbLoader'

    TomvdPeet\BreadcrumbBundle\CacheWarmer\CompiledBreadcrumbCacheWarmer:
        arguments:
            $cacheFile: '%tomvd_peet_breadcrumb.cache_file%'

    TomvdPeet\BreadcrumbBundle\EventListener\BreadcrumbListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: -1 }
