services:
    _defaults:
        public: false
        autoconfigure: true
        autowire: true

    APY\BreadcrumbTrailBundle\:
        resource: '../../*'
        exclude: '../../{Annotation,Resources}'

    APY\BreadcrumbTrailBundle\BreadcrumbTrail\Trail:
        calls:
            - setTemplate: ['%apy_breadcrumb_trail.template%']

    apy_breadcrumb_trail:
        alias: APY\BreadcrumbTrailBundle\BreadcrumbTrail\Trail
        public: true

    APY\BreadcrumbTrailBundle\EventListener\BreadcrumbListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: -1 }
