name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.4', '8.5']

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring, intl
          tools: composer:v2, flex

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dependencies
        uses: ramsey/composer-install@v3

      - name: Run tests
        run: composer run test

  codestyle:
    name: Code style
    runs-on: ubuntu-latest
    container: jakzal/phpqa:php8.4
    steps:
      - uses: actions/checkout@v4
      - name: PHP CS Fixer (via jakzal/phpqa)
        run: php-cs-fixer fix -vv --dry-run

  static:
    name: Static code analysis
    runs-on: ubuntu-latest
    container: jakzal/phpqa
    steps:
      - uses: actions/checkout@v4
      - run: composer install
      - name: PHPStan (via jakzal/phpqa)
        run: phpstan analyze -c .phpstan.neon
